"""
Gemini Client - Slides & Flowcharts Generation
Uses Google Gemini for creating visual learning materials
"""

import google.generativeai as genai
import asyncio
from typing import Dict, Any, List, Optional
import config
import json

class GeminiClient:
    """
    Google Gemini AI client for generating slides and flowcharts
    Specializes in: visual content, structured presentations, diagrams
    """
    
    def __init__(self):
        if not config.GOOGLE_API_KEY:
            raise ValueError("GOOGLE_API_KEY not found in environment")
        
        genai.configure(api_key=config.GOOGLE_API_KEY)
        self.model = genai.GenerativeModel(config.GEMINI_MODEL)
        print(f"✅ Gemini client initialized ({config.GEMINI_MODEL})")
    
    async def generate_slides(
        self,
        topic: str,
        theory_content: str,
        level: str = "beginner",
        count: int = 5
    ) -> Dict[str, Any]:
        """
        Generate interactive slide content
        
        Args:
            topic: Topic name
            theory_content: Theory generated by Claude
            level: Difficulty level
            count: Number of slides to generate
            
        Returns:
            Dict with slides array
        """
        
        prompt = f"""Create {count} educational slides for teaching Python {topic} to {level} students.

Theory context:
{theory_content[:500]}

For each slide, provide:
1. Title (clear, concise)
2. Content (2-3 bullet points or short paragraph)
3. Code example (if applicable)
4. Visual suggestion (what diagram/image would help)

Format as JSON array of slides:
[
  {{
    "slide_number": 1,
    "title": "What is a {topic.capitalize()}?",
    "content": ["point 1", "point 2"],
    "code_example": "# code here" (if applicable),
    "visual_type": "diagram" | "flowchart" | "illustration",
    "visual_description": "what to show"
  }},
  ...
]

Rules:
- One concept per slide
- Keep text minimal
- Include practical examples
- Progress from simple to complex
- Last slide should be "Try it yourself!" challenge

Return ONLY the JSON array, no markdown formatting.
"""

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self.model.generate_content(prompt)
            )
            
            content = response.text.strip()
            
            # Remove markdown code blocks if present
            if content.startswith("```json"):
                content = content.split("```json")[1].split("```")[0].strip()
            elif content.startswith("```"):
                content = content.split("```")[1].split("```")[0].strip()
            
            slides = json.loads(content)
            
            return {
                "success": True,
                "slides": slides,
                "count": len(slides),
                "model": config.GEMINI_MODEL
            }
            
        except json.JSONDecodeError as e:
            print(f"⚠️ Gemini JSON parse error: {e}")
            # Fallback: create basic slides
            return {
                "success": True,
                "slides": self._create_fallback_slides(topic, count),
                "count": count,
                "model": config.GEMINI_MODEL,
                "fallback": True
            }
        except Exception as e:
            print(f"❌ Gemini slides error: {e}")
            return {
                "success": False,
                "error": str(e),
                "slides": []
            }
    
    async def generate_flowcharts(
        self,
        topic: str,
        concept: str,
        count: int = 2
    ) -> Dict[str, Any]:
        """
        Generate Mermaid flowcharts for visual learning
        
        Args:
            topic: Main topic
            concept: Specific concept to visualize
            count: Number of flowcharts
            
        Returns:
            Dict with mermaid code for flowcharts
        """
        
        prompt = f"""Create {count} Mermaid.js flowcharts to explain Python {topic} - specifically {concept}.

Each flowchart should:
1. Show a clear process or concept flow
2. Use simple, beginner-friendly language
3. Have 5-8 nodes maximum
4. Use colors for visual distinction

Format as JSON array:
[
  {{
    "title": "descriptive title",
    "description": "what this flowchart shows",
    "mermaid_code": "graph TD\\n  A[Start]-->B[Step]",
    "explanation": "what each part means"
  }},
  ...
]

Example for "variable assignment":
```json
[
  {{
    "title": "Creating a Variable",
    "description": "How Python creates and stores a variable",
    "mermaid_code": "graph LR\\n  A[Choose Name]-->B[Use = Sign]\\n  B-->C[Assign Value]\\n  C-->D[Variable Created!]\\n  style A fill:#e1f5ff\\n  style D fill:#e1ffe1",
    "explanation": "Variables are created in 3 steps: name, equals, value"
  }}
]
```

Return ONLY the JSON array for {topic}.
"""

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self.model.generate_content(prompt)
            )
            
            content = response.text.strip()
            
            # Clean markdown
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()
            
            flowcharts = json.loads(content)
            
            return {
                "success": True,
                "flowcharts": flowcharts,
                "count": len(flowcharts),
                "model": config.GEMINI_MODEL
            }
            
        except json.JSONDecodeError as e:
            print(f"⚠️ Gemini JSON parse error: {e}")
            return {
                "success": True,
                "flowcharts": self._create_fallback_flowchart(topic),
                "count": 1,
                "fallback": True
            }
        except Exception as e:
            print(f"❌ Gemini flowchart error: {e}")
            return {
                "success": False,
                "error": str(e),
                "flowcharts": []
            }
    
    def _create_fallback_slides(self, topic: str, count: int) -> List[Dict]:
        """Create basic slides if AI generation fails"""
        return [
            {
                "slide_number": i + 1,
                "title": f"{topic.capitalize()} - Part {i + 1}",
                "content": [f"Learning about {topic}", "Examples coming soon"],
                "code_example": f"# {topic} example",
                "visual_type": "diagram",
                "visual_description": f"Illustration of {topic}"
            }
            for i in range(count)
        ]
    
    def _create_fallback_flowchart(self, topic: str) -> List[Dict]:
        """Create basic flowchart if AI generation fails"""
        return [{
            "title": f"{topic.capitalize()} Process",
            "description": f"Basic flow of {topic}",
            "mermaid_code": f"graph LR\n  A[Start]-->B[Learn {topic}]\n  B-->C[Practice]\n  C-->D[Master it!]",
            "explanation": f"The learning process for {topic}"
        }]


# Test function
async def test_gemini():
    """Test Gemini client"""
    client = GeminiClient()
    
    print("\n🧪 Testing slides generation...")
    slides_result = await client.generate_slides(
        "variables",
        "Variables are containers for storing data values",
        "beginner",
        3
    )
    if slides_result["success"]:
        print(f"✅ Generated {slides_result['count']} slides")
        print(f"📊 First slide: {slides_result['slides'][0]['title']}")
    else:
        print(f"❌ Error: {slides_result['error']}")
    
    print("\n🧪 Testing flowcharts generation...")
    flow_result = await client.generate_flowcharts(
        "variables",
        "variable assignment process",
        2
    )
    if flow_result["success"]:
        print(f"✅ Generated {flow_result['count']} flowcharts")
        print(f"📈 First: {flow_result['flowcharts'][0]['title']}")
    else:
        print(f"❌ Error: {flow_result['error']}")


if __name__ == "__main__":
    asyncio.run(test_gemini())
